"""Bazarr post-processing hook: build a KinoGloss bilingual track whenever Bazarr
downloads a subtitle.

Bazarr has no plugin API; its extension point is the custom post-processing
command (Settings -> Subtitles -> Post-Processing), which runs once per
downloaded subtitle. Point it at this script, passing three variables:

    "<bazarr python.exe>" "D:\\Projekte\\KinoGloss\\bazarr_hook.py" {{episode}} {{subtitles}} {{subtitles_language_code2}}

- A study-language subtitle arrives (say Russian): it becomes MAIN, and the
  video's English track becomes GLOSS: an English sidecar if there is one,
  else an embedded English text track pulled out with ffmpeg.
- An English subtitle arrives: every study-language sidecar already next to
  the video is (re)glossed with it.

Output is `<video stem>.<lang>.ass` next to the video, so Plex labels it with
the study language; it shows as "ASS" beside the plain "SRT" track.

Settings live in bazarr_hook.json beside this file (see DEFAULTS). Progress
goes to bazarr_hook.log; Bazarr only sees a one-line summary on stdout,
because it logs anything on stderr as an error.

Backfill an existing library without Bazarr:

    python bazarr_hook.py --backfill "E:\\Medien\\Kino" [--dry-run]
"""
from __future__ import annotations

import contextlib
import io
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import kinogloss  # noqa: E402

DEFAULTS = {
    # languages you are learning: a subtitle in one of these becomes MAIN
    "study_languages": ["ru", "pl", "sk", "sr", "hr", "sh", "lt"],
    # the language you already read: it becomes the italic GLOSS
    "gloss_language": "en",
    # which file's timing to keep: "gloss" (English releases usually match the
    # video best) or "main"
    "timestamps": "gloss",
    "output_name": "{stem}.{lang}.ass",
    "gloss_position": "below",
    "font_size": 48,
    "gloss_scale": 0.75,
    # never replace an .ass that KinoGloss did not write
    "overwrite_foreign_ass": False,
}
VIDEO_EXTS = {".mkv", ".mp4", ".avi", ".m4v", ".mov", ".webm"}
MARKER = "; generated by KinoGloss"
LOG = HERE / "bazarr_hook.log"


def load_config() -> dict:
    cfg = dict(DEFAULTS)
    path = HERE / "bazarr_hook.json"
    if path.exists():
        cfg.update(json.loads(path.read_text(encoding="utf-8")))
    return cfg


def log(msg: str) -> None:
    with LOG.open("a", encoding="utf-8") as f:
        f.write(f"{time.strftime('%Y-%m-%d %H:%M:%S')} {msg}\n")


def unquote(arg: str) -> str:
    # Bazarr splits the command with shlex(posix=False) on Windows, which leaves
    # the double quotes it added around each variable inside the argument.
    return arg.strip().strip('"').strip("'")


def sidecars(video: Path, lang: str) -> list[Path]:
    """Plain, then SDH/HI, SRT sidecars for `lang`; forced tracks are skipped
    because they only cover on-screen text."""
    stem = video.with_suffix("").name
    order = [f"{stem}.{lang}.srt", f"{stem}.{lang}.sdh.srt", f"{stem}.{lang}.hi.srt",
             f"{stem}.{lang}.cc.srt"]
    return [video.parent / n for n in order if (video.parent / n).is_file()]


def find_ffmpeg() -> tuple[str | None, str | None]:
    bazarr_bin = Path(r"D:\Program Files\Bazarr\bin\Windows\i386\ffmpeg")
    ff = shutil.which("ffmpeg") or (str(bazarr_bin / "ffmpeg.exe") if (bazarr_bin / "ffmpeg.exe").exists() else None)
    fp = shutil.which("ffprobe") or (str(bazarr_bin / "ffprobe.exe") if (bazarr_bin / "ffprobe.exe").exists() else None)
    return ff, fp


ISO3 = {"en": ["eng", "en"], "ru": ["rus", "ru"], "pl": ["pol", "pl"], "de": ["ger", "deu", "de"]}


def extract_embedded(video: Path, lang: str, workdir: Path) -> Path | None:
    """Pull the first non-forced text subtitle track in `lang` out of the video."""
    ffmpeg, ffprobe = find_ffmpeg()
    if not ffmpeg or not ffprobe:
        return None
    probe = subprocess.run(
        [ffprobe, "-v", "error", "-select_streams", "s", "-show_entries",
         "stream=index,codec_name:stream_tags=language,title:stream_disposition=forced",
         "-of", "json", str(video)],
        capture_output=True, text=True, encoding="utf-8", errors="replace")
    try:
        streams = json.loads(probe.stdout or "{}").get("streams", [])
    except json.JSONDecodeError:
        return None
    wanted = ISO3.get(lang, [lang])
    for n, s in enumerate(streams):
        tags = s.get("tags", {})
        if (tags.get("language", "").lower() in wanted
                and s.get("codec_name") in ("subrip", "ass", "ssa", "mov_text", "webvtt", "text")
                and not s.get("disposition", {}).get("forced")
                and "forced" not in tags.get("title", "").lower()):
            out = workdir / f"embedded.{lang}.srt"
            r = subprocess.run([ffmpeg, "-v", "error", "-y", "-i", str(video), "-map", f"0:s:{n}",
                                "-f", "srt", str(out)], capture_output=True)
            if r.returncode == 0 and out.stat().st_size > 0:
                return out
    return None


def ours_or_absent(path: Path, cfg: dict) -> bool:
    if not path.exists() or cfg["overwrite_foreign_ass"]:
        return True
    head = path.read_text(encoding="utf-8", errors="replace")[:400]
    return MARKER in head or "KinoGloss" in head


def gloss(video: Path, main_srt: Path, lang: str, gloss_srt: Path, cfg: dict, dry: bool = False) -> str:
    out = video.parent / cfg["output_name"].format(stem=video.with_suffix("").name, lang=lang)
    if out.resolve() == main_srt.resolve():
        return f"skip {main_srt.name}: would overwrite itself"
    if not ours_or_absent(out, cfg):
        return f"skip {out.name}: an .ass not written by KinoGloss is already there"
    if dry:
        return f"would write {out.name}  (main {main_srt.name}, gloss {gloss_srt.name})"
    argv = [str(main_srt), str(gloss_srt), "-o", str(out), "--format", "ass",
            "--timestamps", "2" if cfg["timestamps"] == "gloss" else "1",
            "--gloss-position", cfg["gloss_position"],
            "--font-size", str(cfg["font_size"]), "--gloss-scale", str(cfg["gloss_scale"])]
    report = io.StringIO()
    with contextlib.redirect_stderr(report):
        rc = kinogloss.main(argv)
    for line in report.getvalue().splitlines():
        log(f"  {line}")
    if rc != 0:
        return f"KinoGloss failed ({rc}) for {main_srt.name}"
    text = out.read_text(encoding="utf-8")
    if MARKER not in text[:400]:
        out.write_text(text.replace("[Script Info]", f"[Script Info]\n{MARKER}", 1), encoding="utf-8")
    return f"wrote {out.name}"


def handle(video: Path, subtitle: Path, lang: str, cfg: dict, dry: bool = False) -> list[str]:
    lang = lang.lower()
    study, gl = cfg["study_languages"], cfg["gloss_language"]
    if subtitle.suffix.lower() != ".srt":
        return [f"skip {subtitle.name}: KinoGloss reads SRT only"]
    results = []
    with tempfile.TemporaryDirectory() as tmp:
        if lang in study:
            gloss_srt = next(iter(sidecars(video, gl)), None) or extract_embedded(video, gl, Path(tmp))
            if gloss_srt is None:
                return [f"no {gl} subtitle for {video.name} yet; will gloss when one arrives"]
            results.append(gloss(video, subtitle, lang, gloss_srt, cfg, dry))
        elif lang == gl:
            for other in study:
                for main_srt in sidecars(video, other)[:1]:
                    results.append(gloss(video, main_srt, other, subtitle, cfg, dry))
            if not results:
                results.append(f"no study-language sidecar next to {video.name}")
        else:
            results.append(f"{lang} is neither a study language nor {gl}; nothing to do")
    return results


def backfill(root: Path, cfg: dict, dry: bool) -> None:
    for video in sorted(p for p in root.rglob("*") if p.suffix.lower() in VIDEO_EXTS):
        if any(part.lower() in ("featurettes", "deleted scenes", "trailers", "interviews",
                                "behind the scenes", "extras", "_torrent-extras") for part in video.parts):
            continue
        for lang in cfg["study_languages"]:
            main = sidecars(video, lang)
            if main:
                for r in handle(video, main[0], lang, cfg, dry):
                    print(f"{video.parent.name}: {r}")


def main(argv: list[str]) -> int:
    cfg = load_config()
    if argv[:1] == ["--backfill"]:
        backfill(Path(unquote(argv[1])), cfg, dry="--dry-run" in argv)
        return 0
    if len(argv) != 3:
        print("usage: bazarr_hook.py {{episode}} {{subtitles}} {{subtitles_language_code2}}")
        return 0  # never make Bazarr log a failure for a misconfigured command
    video, subtitle, lang = Path(unquote(argv[0])), Path(unquote(argv[1])), unquote(argv[2])
    log(f"bazarr: {subtitle.name} [{lang}] for {video.name}")
    try:
        results = handle(video, subtitle, lang, cfg)
    except Exception as e:  # keep Bazarr's own processing unaffected
        log(f"  error: {e!r}")
        results = [f"error: {e}"]
    for r in results:
        log(f"  {r}")
    print("KinoGloss: " + "; ".join(results))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
